[package]
name = "macros"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = { git="https://github.com/dtolnay/paste", version = "1.0"}
